[plc]
address = 192.168.20.192:502

[redis]
address = 127.0.0.1:6379
db = 0

[server]
url = http://localhost:8000/receive
enable_post = true
; 【新增】POST 推送间隔（每多少个采集周期发送一次）
; 假设主循环 100ms，设置为 50 表示每 5 秒发送一次
post_interval = 45

[paths]
log_dir = logs
backup_dir = backups
; 【新增】本地文件保存间隔（每多少个采集周期保存一次）
; 设置为 20 表示每 2 秒保存一次
save_interval = 16